### ISSUE TITLE
Clicking "Open Unofficial Mod Repo" Does nothing

### ISSUE THREAD

**Issue by 321nick** [atlanticaccent/starsector-mod-manager-rust#156]
as the title says, no popup or anything.

Heres what my settings and launcher look like RN (if theres a log or smth that would help tell me): 
![image](https://user-images.githubusercontent.com/19196462/170534814-3c3a1255-a3b2-46b2-bb43-7035eda057c4.png)

**Comment by josiah-roberts** [comment]
+1

**Comment by atlanticaccent** [comment]
Yeah this is my bad. When I wrote this feature Wisp's Unofficial Mod Repo had a different schema which has since changed. Because the schema changed, pressing this button pulls the data down then immediately causes the subroutine to crash - thankfully leaving the rest of the app alone. 

Thankfully, fixing this is a pretty small job.

**Comment by superyuuki** [comment]
How is this going?

**Comment by atlanticaccent** [comment]
This should be fixed as of PR #166
